language: node_js
node_js:
    - "8"
env:
    global:
        - NODE_ENV=test
script:
    - npm install
    - npm run test:unit
branches:
    only:
        - master
addons:
    apt:
        packages:
            - libgif-dev
